### ISSUE TITLE
Choosing an appropriate license

### ISSUE THREAD

**Issue by drspangle** [drspangle/infidel-sensor#1]
It's not clear what license that Thomas Sanladerer intended for this project, he just says it's "all free". We should check to see what he was actually intending -- perhaps it's a CC share-alike license or something.

**Comment by imitation** [comment]
"All free" literally means "CC-0 / PD / no rights reserved" in this case. Use in any and every way you deem appropriate - no attribution required (though appreciated). 
Allowed use also includes sharing and using any of provided files under a different license.

**Comment by drspangle** [comment]
Added LICENSE, fixed in 5d8666c1a287c430bc7336bd76a3391ac569ba7b.
