### ISSUE TITLE
[FEATURE REQUEST] Add Kitspace one click pricing

### ISSUE THREAD

**Issue by darigovresearch** [drspangle/infidel-sensor#19]
[Kitspace](https://kitspace.org/) is a project that really helps with building open source hardware as it allows you to (when properly implemented) have an almost one click pricing for the PCB and electronics components. If setup by the maintainers it would really decrease uncertainty if the components chosen are the ones that work reliably.

We haven't had to implement it yet but it seems relatively straightforward to implement and lets users have self-autonomy to replicate the work, build upon it and put it in the hands of users.

Examples of very good implementations of this are the [Open book](https://kitspace.org/boards/github.com/joeycastillo/the-open-book/open-book/) and [ebook wing](https://kitspace.org/boards/github.com/joeycastillo/the-open-book/ebook-wing/) projects by @joeycastillo

https://kitspace.org/1-click-bom/
https://github.com/kitspace/1clickBOM#readme

Would also resolve issue #18 as well

**Comment by drspangle** [comment]
What is required to do this?

**Comment by drspangle** [comment]
@darigovresearch If you want to set this up and create a PR, I will review it.

**Comment by darigovresearch** [comment]
Thanks @drspangle, pull request #23 should contain the files that are required for this repository

**Comment by drspangle** [comment]
Addressed in #23.

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/github.com/drspangle/infidel-sensor/
