### ISSUE TITLE
[FEATURE REQUEST] KiCad version of PCB

### ISSUE THREAD

**Issue by darigovresearch** [drspangle/infidel-sensor#24]
We may get more contributions/improvements to the system if it is in an open source PCB format like KiCad as it would reduce the barrier to entry for new users. Was wondering if the maintainers or someone from the community would be interested in trying this out.

https://www.kicad.org/

**Comment by midopple** [comment]
I have add the KiCad Files for the SMT Version, see Pul request #26

**Comment by darigovresearch** [comment]
@midopple thanks for taking the time to do this, have managed to see if we can open the files & it seems to be working. Unsure if the porting has resulted in any differences from the original as we're still relatively new to PCB design & KiCad

![image](https://user-images.githubusercontent.com/30328618/115121379-5983d200-9faa-11eb-8fc3-a8b45ecbcc81.png)

**Comment by drspangle** [comment]
I can't tell if there are any differences, and this will potentially create issues if both sets of schematics are not updated, but I'm of the opinion that if this helps the project gain traction among the community then it's worth the risk. Addressed in #26.

**Comment by darigovresearch** [comment]
@midopple thanks for the pull request & @drspangle thanks for merging it. We also believe that having both copies is worth the risk if it encourages people to join the project. Keeping it updated in KiCad could also be good easy pull requests for people who want to get started in contributing to KiCad projects.
