### ISSUE TITLE
Capacitor grounds not connected

### ISSUE THREAD

**Issue by eltobu** [drspangle/infidel-sensor#27]
As can be seen in the screenshots below, the grounds of the two capacitors are connected to each other and a ground fill island on the bottom side.
This ground fill island is then not connected to the rest of ground, but it should be.
Top side:
![image](https://user-images.githubusercontent.com/3285034/115861779-836a4800-a433-11eb-9c87-c940857e69c7.png)
Bottom side:
![image](https://user-images.githubusercontent.com/3285034/115861807-8e24dd00-a433-11eb-89cf-3882bb4ecabc.png)

**Comment by blurfl** [comment]
That's a good find. Could you add pics to PR #28 to show the fix?

**Comment by eltobu** [comment]
Yeah, would have been a good idea in the first place.
I have added screenshots of the full board and both layers.

**Comment by darigovresearch** [comment]
@eltobu good catch, & @blurfl thanks for the fix. Can anyone tell if this issue is also in the KiCad version of the project as it was autogenerated a week before this fix?

**Comment by drspangle** [comment]
@darigovresearch As far as I can tell, #28 addressed the problem in the KiCad version, and #29 addressed the problem in the EAGLE version.

**Comment by darigovresearch** [comment]
Thanks @drspangle for confirming & @blurfl for the fix!
