### ISSUE TITLE
Add kitspace link to readme

### ISSUE THREAD

**Issue by darigovresearch** [drspangle/infidel-sensor#30]
Now we have an easy way to order PCBs & electronic parts it would be good to make it discoverable from the electronics section of the readme

See below for context 
- https://github.com/drspangle/infidel-sensor/issues/19
- https://kitspace.org/boards/github.com/drspangle/infidel-sensor/

**Comment by darigovresearch** [comment]
Pull request #31 would resolve this issue if merged

**Comment by drspangle** [comment]
This was addressed in #31.
