### ISSUE TITLE
[FEATURE REQUEST] Molten plastic version of the sensor

### ISSUE THREAD

**Issue by darigovresearch** [drspangle/infidel-sensor#34]
We know it's not particularly easy to make 3D printer ready filament from recycled material but if the sensor could work on molten extruded filament as well it may unlock with other open source machines like the precious plastic extrusion machine to make dimensionally accurate material - https://preciousplastic.com/solutions/machines/basic

In the video Tom mentions that the current design is not particularly optimised for molten extruded material as the pressure of the spring and bearings are too high and may "ovalise" the filament. What would be needed to be adjusted to the current design for the above use case to be feasible?

Video in question - https://www.youtube.com/watch?v=RYgdLPe_T0c

**Comment by drspangle** [comment]
This isn't feasible with this kind of filament sensor design. To measure molten filament requires a solution which doesn't involve putting any sort of pressure on the filament -- optical sensors are the only feasible approach. This is way out of scope for this kind of low cost filament measurement solution.
