### ISSUE TITLE
Can it output analog values from 0-5V

### ISSUE THREAD

**Issue by TeslaMaker** [drspangle/infidel-sensor#35]
im thinking of using this for a filament extruder with the firmware called mackerel
https://github.com/filipmu/Marlin-Mackerel
this accepts 0-5v for the sensor value , is it possible to tweak something here so as to give a pwm signal or analog from 0-5v?

**Comment by drspangle** [comment]
I believe that the firmware provided by @midopple already has this capability. See: https://github.com/drspangle/infidel-sensor/blob/main/firmware/README.md#analog-output

You would need to use additional circuitry to boost the gain on this output to within the range you want:

> The range goes from 1.42 VDC to 2.14 VDC . The voltage is the analog for the diameter: 1.73V is equal to 1.73mm diameter.

I believe that this output is created through PWM, as there is no other way I can think of which would be possible to generate this voltage using the facilities on the hardware as-is.
