### ISSUE TITLE
[BUG] No link to documentation in readme

### ISSUE THREAD

**Issue by darigovresearch** [drspangle/infidel-sensor#42]
**Describe the bug**
There is no link in the readme to point to the newly generated documentation - https://drspangle.github.io/infidel-sensor/

**To Reproduce**
1. Go to [README](https://github.com/drspangle/infidel-sensor)

**Expected behavior**
Have a link in the readme to point to the documentation

**Screenshots**
N/A

**Additional context**
N/A

**Comment by drspangle** [comment]
Fixed in #49.
