### ISSUE TITLE
[FEATURE] Add instructions on how to build the documentation

### ISSUE THREAD

**Issue by darigovresearch** [drspangle/infidel-sensor#43]
**Is your feature request related to a problem? Please describe.**
New users will not know how to build the documentation if they wish to make contributions

**Describe the solution you'd like**
Small introduction & instructions on how to build either in the docs or the readme 

**Describe alternatives you've considered**
Could be only in either the readme or the docs but would be helpful to have both depending on where the user starts from

**Additional context**
N/A

**Comment by drspangle** [comment]
This isn't necessary anymore since the docs get automatically rebuilt on every release.
