### ISSUE TITLE
[FEATURE] Add auto-build of documentation as preview in a Pull request

### ISSUE THREAD

**Issue by darigovresearch** [drspangle/infidel-sensor#44]
**Is your feature request related to a problem? Please describe.**
When making a pull request aiming to improve the documentation, it is hard to test that the new changes does not break the original documentation 

**Describe the solution you'd like**
Figure out a way to auto-build it in a check when merging a pull request

**Describe alternatives you've considered**
Manually building but this takes time

**Additional context**
Example for this feature using readthedocs can be found in the [Manim Community repository](https://github.com/ManimCommunity/manim/)

Example pull request - https://github.com/ManimCommunity/manim/pull/1712
Example build for the pull request (may not last after merging) - https://manimce--1712.org.readthedocs.build/en/1712/

**Comment by darigovresearch** [comment]
@Darylgolden do you know how this was done on the Manim Community repository?

**Comment by WampyCakes** [comment]
Are you referring to [this RTD setting](https://docs.readthedocs.io/en/stable/pull-requests.html)?

**Comment by leonhma** [comment]
You could actually scrap the Workflow Part i Just added in #52 i think, move the Docs to rtd and enable this setting.

**Comment by darigovresearch** [comment]
@leonhma would be very happy to see this feature implemented if you're still up for doing it

**Comment by leonhma** [comment]
Yeah sure but I don't think I'm maintainer yet. (I missed the invite 😬)

**Comment by leonhma** [comment]
Although, it would be better if you @drspangle set up the project on RTD (I don't know if I can add the RTD oath app even as maintainer) setting up the project is quite easy 👍

**Comment by drspangle** [comment]
@leonhma You have the ability to add this to your RTD account -- you just need to add your GitHub account to RTD and then you can authorize the application to pull in the repo from GitHub, not the other way around.

If you already sign in with RTD using your GitHub account, you're done.

https://docs.readthedocs.io/en/stable/connected-accounts.html

**Comment by leonhma** [comment]
yeah but... it also needs this 'oauth app' or whatever that automatically builds on pull requests and i dont think you can do that as a maintainer? i can try though..

**Comment by leonhma** [comment]
https://infidel-sensor.readthedocs.io/en/latest/ here it is. it tells me that i dont have the permissions to set up a webhook, though.

**Comment by drspangle** [comment]
@leonhma I can set up the webhook. You will need to send me the payload URL and secret via a secure medium -- you can find me on Keybase at the same username as my GitHub account.

**Comment by leonhma** [comment]
@drspangle I think you can close this, should be resolved via the setting in RTD

**Comment by drspangle** [comment]
Agreed. Closing now.
